### ISSUE TITLE
Sound.js not working in firefox 25.0

### ISSUE THREAD

**Issue by logeshvc** [CreateJS/SoundJS#82]
Hi 

My sound.js version is 0.4.1 , It is throwing following error in console 

" b.noteOn is not a function" .  Kindly advice me what is the solution for the error
